[api]
[33m╷[0m[0m
[33m│[0m [0m[1m[33mWarning: [0m[0m[1mNo outputs found[0m
[33m│[0m [0m
[33m│[0m [0m[0mThe state file either has no
[33m│[0m [0moutputs defined, or all the
[33m│[0m [0mdefined outputs are empty.
[33m│[0m [0mPlease define an output in
[33m│[0m [0myour configuration with the
[33m│[0m [0m`output` keyword and run
[33m│[0m [0m`terraform refresh` for it to
[33m│[0m [0mbecome available. If you are
[33m│[0m [0musing interpolation, please
[33m│[0m [0mverify the interpolated value
[33m│[0m [0mis not empty. You can use the
[33m│[0m [0m`terraform console` command to
[33m│[0m [0massist.
[33m╵[0m[0m

[payments]
[33m╷[0m[0m
[33m│[0m [0m[1m[33mWarning: [0m[0m[1mNo outputs found[0m
[33m│[0m [0m
[33m│[0m [0m[0mThe state file either has no
[33m│[0m [0moutputs defined, or all the
[33m│[0m [0mdefined outputs are empty.
[33m│[0m [0mPlease define an output in
[33m│[0m [0myour configuration with the
[33m│[0m [0m`output` keyword and run
[33m│[0m [0m`terraform refresh` for it to
[33m│[0m [0mbecome available. If you are
[33m│[0m [0musing interpolation, please
[33m│[0m [0mverify the interpolated value
[33m│[0m [0mis not empty. You can use the
[33m│[0m [0m`terraform console` command to
[33m│[0m [0massist.
[33m╵[0m[0m

[logs]
[33m╷[0m[0m
[33m│[0m [0m[1m[33mWarning: [0m[0m[1mNo outputs found[0m
[33m│[0m [0m
[33m│[0m [0m[0mThe state file either has no
[33m│[0m [0moutputs defined, or all the
[33m│[0m [0mdefined outputs are empty.
[33m│[0m [0mPlease define an output in
[33m│[0m [0myour configuration with the
[33m│[0m [0m`output` keyword and run
[33m│[0m [0m`terraform refresh` for it to
[33m│[0m [0mbecome available. If you are
[33m│[0m [0musing interpolation, please
[33m│[0m [0mverify the interpolated value
[33m│[0m [0mis not empty. You can use the
[33m│[0m [0m`terraform console` command to
[33m│[0m [0massist.
[33m╵[0m[0m

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/your-key.pem
